chore: add docker-compose.yml
EpamLifeSciencesTeam/cmwl_pipeline_core pull request #4
Opened 2019-12-30 09:52 UTC by Mikhail-Sosnin

2019-12-30 09:54 UTC, iliaonishchenko approved these changes

2019-12-30 21:25 UTC, andreibelov approved these changes
LGTM

2019-12-31 12:46 UTC, DenisVerkhoturov requested changes
Thank you for the pull-request.

You can find some notes below. Also, I wasn't able to deploy this stack, actually, I was but the application was not answering.

2019-12-31 12:46 UTC, DenisVerkhoturov commented on docker-compose.yml
> +      - db
Please add a `newline` at the end of the file.

2019-12-31 12:46 UTC, DenisVerkhoturov commented on docker-compose.yml
> +    image: 'gitlab/gitlab-ce:latest'
`latest` tag brings about non-reproducible builds, I suggest we replace it with actual tag standing behind the `latest` tag which is `12.6.1-ce.0` currently.

2019-12-31 12:46 UTC, DenisVerkhoturov commented on docker-compose.yml
> +      - db
I suggest we add `gitlab` as a dependency as well since our application can't work without it.

2019-12-31 12:46 UTC, DenisVerkhoturov commented on docker-compose.yml
> +      - "5432:5432"
Why do we expose internal things to the outer world?
I suggest we make `db` and `gitlab` inaccessible from the host machines, create `network`, and add coresponding networks to the services:
```yml
version: "3"
services:
  db:
    # Other properties but no ports exposed
    networks:
      - db_network

  gitlab:
    # Other properties but no ports exposed
    networks:
      - git_network

  cromwell_pipeline:
    # Other properties
    ports:
      - 8080:8080
    networks:
      - db_network
      - git_network

networks:
  db_network:
    driver: overlay
  git_network:
    driver: overlay
```

2020-03-16 13:01 UTC, DenisVerkhoturov approved these changes
Looks good to me!:+1:

2020-03-16 13:10 UTC, merged